### ISSUE TITLE
loading NWA12.COBALT example on gaea

### ISSUE THREAD

**Issue by eric-mortenson** [NOAA-GFDL/CEFI-regional-MOM6#51]
I am now on the gaea system, and I tried to follow the wiki on how to setup the NWA12.COBALT example there (https://github.com/NOAA-GFDL/CEFI-regional-MOM6/tree/main/exps). I was able to build, but when I tried to run, I had a couple problems:

-1- when I try to run, the run.sub file crashes because it does not point to the right MOM6SIS2 directory:
slurmstepd: error: execve(): /autofs/ncrc-svm1_home1/Eric.Mortenson/CEFI-regional-MOM6/exps/NWA12.COBALT/./builds/build/gaea-ncrc5.intel23/ocean_ice/repro/MOM6SIS2: No such file or directory

I fixed above by creating a virtual path in the exps/NWA12.COBALT directory:ln -s /na1_home1/Eric.Mortenson/CEFI-regional-MOM6/builds/build/gaea-ncrc5.intel23/ocean_ice/repro/MOM6SIS2 .

-2- after that, the read of input.nml causes a crash because it does not exist. I fixed this before by changing the name of input.nml_24hr to input.nml (and I had the same issue when trying to run the 1D experiment earlier).

I was able to submit it after those fixes, but I thought you'd like to know about those two issues.

**Comment by yichengt900** [comment]
@eric-mortenson, glad to hear you are able to run the `NWA12.COBALT` case, and good catch. At the moment, instead of using `run.sub`, we are using [driver.sh ](https://github.com/NOAA-GFDL/CEFI-regional-MOM6/blob/main/exps/NWA12.COBALT/driver.sh)to run this test case as one of our regression tests. I will update `run.sub` accordingly to avoid any confusion in the future.
